generatorName: typescript
templateDir: templates
importFileExtension: .js
supportsES6: true
platform: node
modelPackage: types
globalProperties:
    supportingFiles: types/index.ts
    models: ""
files:
    model/index.mustache:
        templateType: SupportingFiles
        destinationFilename: types/index.ts
