/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

export interface ClusterVolumePublishStatusInner {
    /**
     * The ID of the Swarm node the volume is published on.
     */
    NodeID?: string;

    /**
     * The published state of the volume. * &#x60;pending-publish&#x60; The volume should be published to this node, but the call to the controller plugin to do so has not yet been successfully completed. * &#x60;published&#x60; The volume is published successfully to the node. * &#x60;pending-node-unpublish&#x60; The volume should be unpublished from the node, and the manager is awaiting confirmation from the worker that it has done so. * &#x60;pending-controller-unpublish&#x60; The volume is successfully unpublished from the node, but has not yet been successfully unpublished on the controller.
     */
    State?: ClusterVolumePublishStatusInnerStateEnum;

    /**
     * A map of strings to strings returned by the CSI controller plugin when a volume is published.
     */
    PublishContext?: { [key: string]: string };
}

export type ClusterVolumePublishStatusInnerStateEnum =
    | 'pending-publish'
    | 'published'
    | 'pending-node-unpublish'
    | 'pending-controller-unpublish';
