/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * All CPU stats aggregated since container inception.
 */
export interface ContainerCPUUsage {
    /**
     * Total CPU time consumed in nanoseconds (Linux) or 100\&#39;s of nanoseconds (Windows).
     */
    TotalUsage?: number;

    /**
     * Total CPU time (in nanoseconds) consumed per core (Linux).  This field is Linux-specific when using cgroups v1. It is omitted when using cgroups v2 and Windows containers.
     */
    PercpuUsage?: Array<number> | null;

    /**
     * Time (in nanoseconds) spent by tasks of the cgroup in kernel mode (Linux), or time spent (in 100\&#39;s of nanoseconds) by all container processes in kernel mode (Windows).  Not populated for Windows containers using Hyper-V isolation.
     */
    UsageInKernelmode?: number;

    /**
     * Time (in nanoseconds) spent by tasks of the cgroup in user mode (Linux), or time spent (in 100\&#39;s of nanoseconds) by all container processes in kernel mode (Windows).  Not populated for Windows containers using Hyper-V isolation.
     */
    UsageInUsermode?: number;
}
