/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Summary of health status  Added in v1.52, before that version all container summary not include Health. After this attribute introduced, it includes containers with no health checks configured, or containers that are not running with none
 */
export interface ContainerSummaryHealth {
    /**
     * the health status of the container
     */
    Status?: ContainerSummaryHealthStatusEnum;

    /**
     * FailingStreak is the number of consecutive failures
     */
    FailingStreak?: number;
}

export type ContainerSummaryHealthStatusEnum =
    | 'none'
    | 'starting'
    | 'healthy'
    | 'unhealthy';
