/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Aggregates the network stats of one container
 */
export interface ContainerNetworkStats {
    /**
     * Bytes received. Windows and Linux.
     */
    RxBytes?: number;

    /**
     * Packets received. Windows and Linux.
     */
    RxPackets?: number;

    /**
     * Received errors. Not used on Windows.  This field is Linux-specific and always zero for Windows containers.
     */
    RxErrors?: number;

    /**
     * Incoming packets dropped. Windows and Linux.
     */
    RxDropped?: number;

    /**
     * Bytes sent. Windows and Linux.
     */
    TxBytes?: number;

    /**
     * Packets sent. Windows and Linux.
     */
    TxPackets?: number;

    /**
     * Sent errors. Not used on Windows.  This field is Linux-specific and always zero for Windows containers.
     */
    TxErrors?: number;

    /**
     * Outgoing packets dropped. Windows and Linux.
     */
    TxDropped?: number;

    /**
     * Endpoint ID. Not used on Linux.  This field is Windows-specific and omitted for Linux containers.
     */
    EndpointId?: string | null;

    /**
     * Instance ID. Not used on Linux.  This field is Windows-specific and omitted for Linux containers.
     */
    InstanceId?: string | null;
}
