/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * The namespaces that the daemon uses for running containers and plugins in containerd. These namespaces can be configured in the daemon configuration, and are considered to be used exclusively by the daemon, Tampering with the containerd instance may cause unexpected behavior.  As these namespaces are considered to be exclusively accessed by the daemon, it is not recommended to change these values, or to change them to a value that is used by other systems, such as cri-containerd.
 */
export interface ContainerdInfoNamespaces {
    /**
     * The default containerd namespace used for containers managed by the daemon.  The default namespace for containers is \&quot;moby\&quot;, but will be suffixed with the &#x60;&lt;uid&gt;.&lt;gid&gt;&#x60; of the remapped &#x60;root&#x60; if user-namespaces are enabled and the containerd image-store is used.
     */
    Containers?: string;

    /**
     * The default containerd namespace used for plugins managed by the daemon.  The default namespace for plugins is \&quot;plugins.moby\&quot;, but will be suffixed with the &#x60;&lt;uid&gt;.&lt;gid&gt;&#x60; of the remapped &#x60;root&#x60; if user-namespaces are enabled and the containerd image-store is used.
     */
    Plugins?: string;
}
