/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type EventActor } from '../models/EventActor.js';

/**
 * EventMessage represents the information an event contains.
 */
export interface EventMessage {
    /**
     * The type of object emitting the event
     */
    Type?: EventMessageTypeEnum;

    /**
     * The type of event
     */
    Action?: string;

    Actor?: EventActor;

    /**
     * Scope of the event. Engine events are &#x60;local&#x60; scope. Cluster (Swarm) events are &#x60;swarm&#x60; scope.
     */
    Scope?: EventMessageScopeEnum;

    /**
     * Timestamp of event
     */
    Time?: number;

    /**
     * Timestamp of event, with nanosecond accuracy
     */
    TimeNano?: number;
}

export type EventMessageTypeEnum =
    | 'builder'
    | 'config'
    | 'container'
    | 'daemon'
    | 'image'
    | 'network'
    | 'node'
    | 'plugin'
    | 'secret'
    | 'service'
    | 'volume';
export type EventMessageScopeEnum = 'local' | 'swarm';
