/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type ImageManifestSummaryAttestationData } from '../models/ImageManifestSummaryAttestationData.js';
import { type ImageManifestSummaryImageData } from '../models/ImageManifestSummaryImageData.js';
import { type ImageManifestSummarySize } from '../models/ImageManifestSummarySize.js';
import { type OCIDescriptor } from '../models/OCIDescriptor.js';

/**
 * ImageManifestSummary represents a summary of an image manifest.
 */
export interface ImageManifestSummary {
    /**
     * ID is the content-addressable ID of an image and is the same as the digest of the image manifest.
     */
    ID: string;

    Descriptor: OCIDescriptor;

    /**
     * Indicates whether all the child content (image config, layers) is fully available locally.
     */
    Available: boolean;

    Size: ImageManifestSummarySize;

    /**
     * The kind of the manifest.  kind         | description -------------|----------------------------------------------------------- image        | Image manifest that can be used to start a container. attestation  | Attestation manifest produced by the Buildkit builder for a specific image manifest.
     */
    Kind: ImageManifestSummaryKindEnum;

    ImageData?: ImageManifestSummaryImageData | null;

    AttestationData?: ImageManifestSummaryAttestationData | null;
}

export type ImageManifestSummaryKindEnum = 'image' | 'attestation' | 'unknown';
