/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type ImageManifestSummary } from '../models/ImageManifestSummary.js';
import { type OCIDescriptor } from '../models/OCIDescriptor.js';

export interface ImageSummary {
    /**
     * ID is the content-addressable ID of an image.  This identifier is a content-addressable digest calculated from the image\&#39;s configuration (which includes the digests of layers used by the image).  Note that this digest differs from the &#x60;RepoDigests&#x60; below, which holds digests of image manifests that reference the image.
     */
    Id: string;

    /**
     * ID of the parent image.  Depending on how the image was created, this field may be empty and is only set for images that were built/created locally. This field is empty if the image was pulled from an image registry.
     */
    ParentId: string;

    /**
     * List of image names/tags in the local image cache that reference this image.  Multiple image tags can refer to the same image, and this list may be empty if no tags reference the image, in which case the image is \&quot;untagged\&quot;, in which case it can still be referenced by its ID.
     */
    RepoTags: Array<string>;

    /**
     * List of content-addressable digests of locally available image manifests that the image is referenced from. Multiple manifests can refer to the same image.  These digests are usually only available if the image was either pulled from a registry, or if the image was pushed to a registry, which is when the manifest is generated and its digest calculated.
     */
    RepoDigests: Array<string>;

    /**
     * Date and time at which the image was created as a Unix timestamp (number of seconds since EPOCH).
     */
    Created: number;

    /**
     * Total size of the image including all layers it is composed of.
     */
    Size: number;

    /**
     * Total size of image layers that are shared between this image and other images.  This size is not calculated by default. &#x60;-1&#x60; indicates that the value has not been set / calculated.
     */
    SharedSize: number;

    /**
     * Total size of the image including all layers it is composed of.  Deprecated: this field is omitted in API v1.44, but kept for backward compatibility. Use Size instead.
     */
    VirtualSize?: number;

    /**
     * User-defined key/value metadata.
     */
    Labels: { [key: string]: string };

    /**
     * Number of containers using this image. Includes both stopped and running containers.  &#x60;-1&#x60; indicates that the value has not been set / calculated.
     */
    Containers: number;

    /**
     * Manifests is a list of manifests available in this image. It provides a more detailed view of the platform-specific image manifests or other image-attached data like build attestations.  WARNING: This is experimental and may change at any time without any backward compatibility.
     */
    Manifests?: Array<ImageManifestSummary>;

    Descriptor?: OCIDescriptor;
}
