/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type Reachability } from '../models/Reachability.js';

/**
 * ManagerStatus represents the status of a manager.  It provides the current status of a node\'s manager component, if the node is a manager.
 */
export interface ManagerStatus {
    Leader?: boolean;

    Reachability?: Reachability;

    /**
     * The IP address and port at which the manager is reachable.
     */
    Addr?: string;
}
