/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type OCIPlatform } from '../models/OCIPlatform.js';

/**
 * A descriptor struct containing digest, media type, and size, as defined in the [OCI Content Descriptors Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md).
 */
export interface OCIDescriptor {
    /**
     * The media type of the object this schema refers to.
     */
    MediaType?: string;

    /**
     * The digest of the targeted content.
     */
    Digest?: string;

    /**
     * The size in bytes of the blob.
     */
    Size?: number;

    /**
     * List of URLs from which this object MAY be downloaded.
     */
    Urls?: Array<string> | null;

    /**
     * Arbitrary metadata relating to the targeted content.
     */
    Annotations?: { [key: string]: string } | null;

    /**
     * Data is an embedding of the targeted content. This is encoded as a base64 string when marshalled to JSON (automatically, by encoding/json). If present, Data can be used directly to avoid fetching the targeted content.
     */
    Data?: string | null;

    Platform?: OCIPlatform | null;

    /**
     * ArtifactType is the IANA media type of this artifact.
     */
    ArtifactType?: string | null;
}
