/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Describes the platform which the image in the manifest runs on, as defined in the [OCI Image Index Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/image-index.md).
 */
export interface OCIPlatform {
    /**
     * The CPU architecture, for example &#x60;amd64&#x60; or &#x60;ppc64&#x60;.
     */
    Architecture?: string;

    /**
     * The operating system, for example &#x60;linux&#x60; or &#x60;windows&#x60;.
     */
    Os?: string;

    /**
     * Optional field specifying the operating system version, for example on Windows &#x60;10.0.19041.1165&#x60;.
     */
    OsVersion?: string;

    /**
     * Optional field specifying an array of strings, each listing a required OS feature (for example on Windows &#x60;win32k&#x60;).
     */
    OsFeatures?: Array<string>;

    /**
     * Optional field specifying a variant of the CPU, for example &#x60;v7&#x60; to specify ARMv7 when architecture is &#x60;arm&#x60;.
     */
    Variant?: string;
}
