/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Available plugins per type.  <p><br /></p>  > **Note**: Only unmanaged (V1) plugins are included in this list. > V1 plugins are \"lazily\" loaded, and are not returned in this list > if there is no resource using the plugin.
 */
export interface PluginsInfo {
    /**
     * Names of available volume-drivers, and network-driver plugins.
     */
    Volume?: Array<string>;

    /**
     * Names of available network-drivers, and network-driver plugins.
     */
    Network?: Array<string>;

    /**
     * Names of available authorization plugins.
     */
    Authorization?: Array<string>;

    /**
     * Names of available logging-drivers, and logging-driver plugins.
     */
    Log?: Array<string>;
}
