/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type JoinTokens } from '../models/JoinTokens.js';
import { type ObjectVersion } from '../models/ObjectVersion.js';
import { type SwarmSpec } from '../models/SwarmSpec.js';
import { type TLSInfo } from '../models/TLSInfo.js';

export interface Swarm {
    /**
     * The ID of the swarm.
     */
    ID?: string;

    Version?: ObjectVersion;

    /**
     * Date and time at which the swarm was initialised in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    CreatedAt?: string;

    /**
     * Date and time at which the swarm was last updated in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    UpdatedAt?: string;

    Spec?: SwarmSpec;

    TLSInfo?: TLSInfo;

    /**
     * Whether there is currently a root CA rotation in progress for the swarm
     */
    RootRotationInProgress?: boolean;

    /**
     * DataPathPort specifies the data path port number for data traffic. Acceptable port range is 1024 to 49151. If no port is set or is set to 0, the default port (4789) is used.
     */
    DataPathPort?: number;

    /**
     * Default Address Pool specifies default subnet pools for global scope networks.
     */
    DefaultAddrPool?: Array<string>;

    /**
     * SubnetSize specifies the subnet size of the networks created from the default subnet pool.
     */
    SubnetSize?: number;

    JoinTokens?: JoinTokens;
}
