/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type SwarmSpecCAConfigExternalCAsInner } from '../models/SwarmSpecCAConfigExternalCAsInner.js';

/**
 * CA configuration.
 */
export interface SwarmSpecCAConfig {
    /**
     * The duration node certificates are issued for.
     */
    NodeCertExpiry?: number;

    /**
     * Configuration for forwarding signing requests to an external certificate authority.
     */
    ExternalCAs?: Array<SwarmSpecCAConfigExternalCAsInner>;

    /**
     * The desired signing CA certificate for all swarm node TLS leaf certificates, in PEM format.
     */
    SigningCACert?: string;

    /**
     * The desired signing CA key for all swarm node TLS leaf certificates, in PEM format.
     */
    SigningCAKey?: string;

    /**
     * An integer whose purpose is to force swarm to generate a new signing CA certificate and key, if none have been specified in &#x60;SigningCACert&#x60; and &#x60;SigningCAKey&#x60;
     */
    ForceRotate?: number;
}
