/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { Commit } from '../models/Commit.js';
import { ContainerdInfo } from '../models/ContainerdInfo.js';
import { DeviceInfo } from '../models/DeviceInfo.js';
import { FirewallInfo } from '../models/FirewallInfo.js';
import { GenericResourcesInner } from '../models/GenericResourcesInner.js';
import { PluginsInfo } from '../models/PluginsInfo.js';
import { RegistryServiceConfig } from '../models/RegistryServiceConfig.js';
import { Runtime } from '../models/Runtime.js';
import { SwarmInfo } from '../models/SwarmInfo.js';
import { SystemInfoDefaultAddressPoolsInner } from '../models/SystemInfoDefaultAddressPoolsInner.js';

export interface SystemInfo {
    /**
     * Unique identifier of the daemon.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: The format of the ID itself is not part of the API, and &gt; should not be considered stable.
     */
    ID?: string;

    /**
     * Total number of containers on the host.
     */
    Containers?: number;

    /**
     * Number of containers with status &#x60;\&quot;running\&quot;&#x60;.
     */
    ContainersRunning?: number;

    /**
     * Number of containers with status &#x60;\&quot;paused\&quot;&#x60;.
     */
    ContainersPaused?: number;

    /**
     * Number of containers with status &#x60;\&quot;stopped\&quot;&#x60;.
     */
    ContainersStopped?: number;

    /**
     * Total number of images on the host.  Both _tagged_ and _untagged_ (dangling) images are counted.
     */
    Images?: number;

    /**
     * Name of the storage driver in use.
     */
    Driver?: string;

    /**
     * Information specific to the storage driver, provided as \&quot;label\&quot; / \&quot;value\&quot; pairs.  This information is provided by the storage driver, and formatted in a way consistent with the output of &#x60;docker info&#x60; on the command line.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: The information returned in this field, including the &gt; formatting of values and labels, should not be considered stable, &gt; and may change without notice.
     */
    DriverStatus?: Array<Array<string>>;

    /**
     * Root directory of persistent Docker state.  Defaults to &#x60;/var/lib/docker&#x60; on Linux, and &#x60;C:\\ProgramData\\docker&#x60; on Windows.
     */
    DockerRootDir?: string;

    Plugins?: PluginsInfo;

    /**
     * Indicates if the host has memory limit support enabled.
     */
    MemoryLimit?: boolean;

    /**
     * Indicates if the host has memory swap limit support enabled.
     */
    SwapLimit?: boolean;

    /**
     * Indicates if the host has kernel memory TCP limit support enabled. This field is omitted if not supported.  Kernel memory TCP limits are not supported when using cgroups v2, which does not support the corresponding &#x60;memory.kmem.tcp.limit_in_bytes&#x60; cgroup.
     */
    KernelMemoryTCP?: boolean;

    /**
     * Indicates if CPU CFS(Completely Fair Scheduler) period is supported by the host.
     */
    CpuCfsPeriod?: boolean;

    /**
     * Indicates if CPU CFS(Completely Fair Scheduler) quota is supported by the host.
     */
    CpuCfsQuota?: boolean;

    /**
     * Indicates if CPU Shares limiting is supported by the host.
     */
    CPUShares?: boolean;

    /**
     * Indicates if CPUsets (cpuset.cpus, cpuset.mems) are supported by the host.  See [cpuset(7)](https://www.kernel.org/doc/Documentation/cgroup-v1/cpusets.txt)
     */
    CPUSet?: boolean;

    /**
     * Indicates if the host kernel has PID limit support enabled.
     */
    PidsLimit?: boolean;

    /**
     * Indicates if OOM killer disable is supported on the host.
     */
    OomKillDisable?: boolean;

    /**
     * Indicates IPv4 forwarding is enabled.
     */
    IPv4Forwarding?: boolean;

    /**
     * Indicates if &#x60;bridge-nf-call-iptables&#x60; is available on the host when the daemon was started.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: netfilter module is now loaded on-demand and no longer &gt; during daemon startup, making this field obsolete. This field is always &gt; &#x60;false&#x60; and will be removed in a API v1.49.
     */
    BridgeNfIptables?: boolean;

    /**
     * Indicates if &#x60;bridge-nf-call-ip6tables&#x60; is available on the host.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: netfilter module is now loaded on-demand, and no longer &gt; during daemon startup, making this field obsolete. This field is always &gt; &#x60;false&#x60; and will be removed in a API v1.49.
     */
    BridgeNfIp6tables?: boolean;

    /**
     * Indicates if the daemon is running in debug-mode / with debug-level logging enabled.
     */
    Debug?: boolean;

    /**
     * The total number of file Descriptors in use by the daemon process.  This information is only returned if debug-mode is enabled.
     */
    NFd?: number;

    /**
     * The  number of goroutines that currently exist.  This information is only returned if debug-mode is enabled.
     */
    NGoroutines?: number;

    /**
     * Current system-time in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    SystemTime?: string;

    /**
     * The logging driver to use as a default for new containers.
     */
    LoggingDriver?: string;

    /**
     * The driver to use for managing cgroups.
     */
    CgroupDriver?: SystemInfoCgroupDriverEnum;

    /**
     * The version of the cgroup.
     */
    CgroupVersion?: SystemInfoCgroupVersionEnum;

    /**
     * Number of event listeners subscribed.
     */
    NEventsListener?: number;

    /**
     * Kernel version of the host.  On Linux, this information obtained from &#x60;uname&#x60;. On Windows this information is queried from the &lt;kbd&gt;HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\&lt;/kbd&gt; registry value, for example _\&quot;10.0 14393 (14393.1198.amd64fre.rs1_release_sec.170427-1353)\&quot;_.
     */
    KernelVersion?: string;

    /**
     * Name of the host\&#39;s operating system, for example: \&quot;Ubuntu 24.04 LTS\&quot; or \&quot;Windows Server 2016 Datacenter\&quot;
     */
    OperatingSystem?: string;

    /**
     * Version of the host\&#39;s operating system  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: The information returned in this field, including its &gt; very existence, and the formatting of values, should not be considered &gt; stable, and may change without notice.
     */
    OSVersion?: string;

    /**
     * Generic type of the operating system of the host, as returned by the Go runtime (&#x60;GOOS&#x60;).  Currently returned values are \&quot;linux\&quot; and \&quot;windows\&quot;. A full list of possible values can be found in the [Go documentation](https://go.dev/doc/install/source#environment).
     */
    OSType?: string;

    /**
     * Hardware architecture of the host, as returned by the Go runtime (&#x60;GOARCH&#x60;).  A full list of possible values can be found in the [Go documentation](https://go.dev/doc/install/source#environment).
     */
    Architecture?: string;

    /**
     * The number of logical CPUs usable by the daemon.  The number of available CPUs is checked by querying the operating system when the daemon starts. Changes to operating system CPU allocation after the daemon is started are not reflected.
     */
    NCPU?: number;

    /**
     * Total amount of physical memory available on the host, in bytes.
     */
    MemTotal?: number;

    /**
     * Address / URL of the index server that is used for image search, and as a default for user authentication for Docker Hub and Docker Cloud.
     */
    IndexServerAddress?: string;

    RegistryConfig?: RegistryServiceConfig | null;

    /**
     * User-defined resources can be either Integer resources (e.g, &#x60;SSD&#x3D;3&#x60;) or String resources (e.g, &#x60;GPU&#x3D;UUID1&#x60;).
     */
    GenericResources?: Array<GenericResourcesInner>;

    /**
     * HTTP-proxy configured for the daemon. This value is obtained from the [&#x60;HTTP_PROXY&#x60;](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable. Credentials ([user info component](https://tools.ietf.org/html/rfc3986#section-3.2.1)) in the proxy URL are masked in the API response.  Containers do not automatically inherit this configuration.
     */
    HttpProxy?: string;

    /**
     * HTTPS-proxy configured for the daemon. This value is obtained from the [&#x60;HTTPS_PROXY&#x60;](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable. Credentials ([user info component](https://tools.ietf.org/html/rfc3986#section-3.2.1)) in the proxy URL are masked in the API response.  Containers do not automatically inherit this configuration.
     */
    HttpsProxy?: string;

    /**
     * Comma-separated list of domain extensions for which no proxy should be used. This value is obtained from the [&#x60;NO_PROXY&#x60;](https://www.gnu.org/software/wget/manual/html_node/Proxies.html) environment variable.  Containers do not automatically inherit this configuration.
     */
    NoProxy?: string;

    /**
     * Hostname of the host.
     */
    Name?: string;

    /**
     * User-defined labels (key/value metadata) as set on the daemon.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Note**: When part of a Swarm, nodes can both have _daemon_ labels, &gt; set through the daemon configuration, and _node_ labels, set from a &gt; manager node in the Swarm. Node labels are not included in this &gt; field. Node labels can be retrieved using the &#x60;/nodes/(id)&#x60; endpoint &gt; on a manager node in the Swarm.
     */
    Labels?: Array<string>;

    /**
     * Indicates if experimental features are enabled on the daemon.
     */
    ExperimentalBuild?: boolean;

    /**
     * Version string of the daemon.
     */
    ServerVersion?: string;

    /**
     * List of [OCI compliant](https://github.com/opencontainers/runtime-spec) runtimes configured on the daemon. Keys hold the \&quot;name\&quot; used to reference the runtime.  The Docker daemon relies on an OCI compliant runtime (invoked via the &#x60;containerd&#x60; daemon) as its interface to the Linux kernel namespaces, cgroups, and SELinux.  The default runtime is &#x60;runc&#x60;, and automatically configured. Additional runtimes can be configured by the user and will be listed here.
     */
    Runtimes?: { [key: string]: Runtime };

    /**
     * Name of the default OCI runtime that is used when starting containers.  The default can be overridden per-container at create time.
     */
    DefaultRuntime?: string;

    Swarm?: SwarmInfo;

    /**
     * Indicates if live restore is enabled.  If enabled, containers are kept running when the daemon is shutdown or upon daemon start if running containers are detected.
     */
    LiveRestoreEnabled?: boolean;

    /**
     * Represents the isolation technology to use as a default for containers. The supported values are platform-specific.  If no isolation value is specified on daemon start, on Windows client, the default is &#x60;hyperv&#x60;, and on Windows server, the default is &#x60;process&#x60;.  This option is currently not used on other platforms.
     */
    Isolation?: SystemInfoIsolationEnum;

    /**
     * Name and, optional, path of the &#x60;docker-init&#x60; binary.  If the path is omitted, the daemon searches the host\&#39;s &#x60;$PATH&#x60; for the binary and uses the first result.
     */
    InitBinary?: string;

    ContainerdCommit?: Commit;

    RuncCommit?: Commit;

    InitCommit?: Commit;

    /**
     * List of security features that are enabled on the daemon, such as apparmor, seccomp, SELinux, user-namespaces (userns), rootless and no-new-privileges.  Additional configuration options for each security feature may be present, and are included as a comma-separated list of key/value pairs.
     */
    SecurityOptions?: Array<string>;

    /**
     * Reports a summary of the product license on the daemon.  If a commercial license has been applied to the daemon, information such as number of nodes, and expiration are included.
     */
    ProductLicense?: string;

    /**
     * List of custom default address pools for local networks, which can be specified in the daemon.json file or dockerd option.  Example: a Base \&quot;10.10.0.0/16\&quot; with Size 24 will define the set of 256 10.10.[0-255].0/24 address pools.
     */
    DefaultAddressPools?: Array<SystemInfoDefaultAddressPoolsInner>;

    FirewallBackend?: FirewallInfo | null;

    /**
     * List of devices discovered by device drivers.  Each device includes information about its source driver, kind, name, and additional driver-specific attributes.
     */
    DiscoveredDevices?: Array<DeviceInfo>;

    /**
     * List of warnings / informational messages about missing features, or issues related to the daemon configuration.  These messages can be printed by the client as information to the user.
     */
    Warnings?: Array<string>;

    /**
     * List of directories where (Container Device Interface) CDI specifications are located.  These specifications define vendor-specific modifications to an OCI runtime specification for a container being created.  An empty list indicates that CDI device injection is disabled.  Note that since using CDI device injection requires the daemon to have experimental enabled. For non-experimental daemons an empty list will always be returned.
     */
    CDISpecDirs?: Array<string>;

    Containerd?: ContainerdInfo | null;
}

export type SystemInfoCgroupDriverEnum = 'cgroupfs' | 'systemd' | 'none';
export type SystemInfoCgroupVersionEnum = '1' | '2';
export type SystemInfoIsolationEnum = 'default' | 'hyperv' | 'process' | '';
