/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type SystemVersionComponentsInner } from '../models/SystemVersionComponentsInner.js';
import { type SystemVersionPlatform } from '../models/SystemVersionPlatform.js';

/**
 * Response of Engine API: GET \"/version\"
 */
export interface SystemVersion {
    Platform?: SystemVersionPlatform;

    /**
     * Information about system components
     */
    Components?: Array<SystemVersionComponentsInner>;

    /**
     * The version of the daemon
     */
    Version?: string;

    /**
     * The default (and highest) API version that is supported by the daemon
     */
    ApiVersion?: string;

    /**
     * The minimum API version that is supported by the daemon
     */
    MinAPIVersion?: string;

    /**
     * The Git commit of the source code that was used to build the daemon
     */
    GitCommit?: string;

    /**
     * The version Go used to compile the daemon, and the version of the Go runtime in use.
     */
    GoVersion?: string;

    /**
     * The operating system that the daemon is running on (\&quot;linux\&quot; or \&quot;windows\&quot;)
     */
    Os?: string;

    /**
     * The architecture that the daemon is running on
     */
    Arch?: string;

    /**
     * The kernel version (&#x60;uname -r&#x60;) that the daemon is running on.  This field is omitted when empty.
     */
    KernelVersion?: string;

    /**
     * Indicates if the daemon is started with experimental features enabled.  This field is omitted when empty / false.
     */
    Experimental?: boolean;

    /**
     * The date and time that the daemon was compiled.
     */
    BuildTime?: string;
}
