/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Information about the global status of the volume.
 */
export interface ClusterVolumeInfo {
    /**
     * The capacity of the volume in bytes. A value of 0 indicates that the capacity is unknown.
     */
    CapacityBytes?: number;

    /**
     * A map of strings to strings returned from the storage plugin when the volume is created.
     */
    VolumeContext?: { [key: string]: string };

    /**
     * The ID of the volume as returned by the CSI storage plugin. This is distinct from the volume\&#39;s ID as provided by Docker. This ID is never used by the user when communicating with Docker to refer to this volume. If the ID is blank, then the Volume has not been successfully created in the plugin yet.
     */
    VolumeID?: string;

    /**
     * The topology this volume is actually accessible from.
     */
    AccessibleTopology?: Array<{ [key: string]: string }>;
}
