/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type ContainerSummaryHealth } from '../types/ContainerSummaryHealth.js';
import { type ContainerSummaryHostConfig } from '../types/ContainerSummaryHostConfig.js';
import { type ContainerSummaryNetworkSettings } from '../types/ContainerSummaryNetworkSettings.js';
import { type MountPoint } from '../types/MountPoint.js';
import { type OCIDescriptor } from '../types/OCIDescriptor.js';
import { type PortSummary } from '../types/PortSummary.js';

export interface ContainerSummary {
    /**
     * The ID of this container as a 128-bit (64-character) hexadecimal string (32 bytes).
     */
    Id?: string;

    /**
     * The names associated with this container. Most containers have a single name, but when using legacy \&quot;links\&quot;, the container can have multiple names.  For historic reasons, names are prefixed with a forward-slash (&#x60;/&#x60;).
     */
    Names?: Array<string>;

    /**
     * The name or ID of the image used to create the container.  This field shows the image reference as was specified when creating the container, which can be in its canonical form (e.g., &#x60;docker.io/library/ubuntu:latest&#x60; or &#x60;docker.io/library/ubuntu@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782&#x60;), short form (e.g., &#x60;ubuntu:latest&#x60;)), or the ID(-prefix) of the image (e.g., &#x60;72297848456d&#x60;).  The content of this field can be updated at runtime if the image used to create the container is untagged, in which case the field is updated to contain the the image ID (digest) it was resolved to in its canonical, non-truncated form (e.g., &#x60;sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782&#x60;).
     */
    Image?: string;

    /**
     * The ID (digest) of the image that this container was created from.
     */
    ImageID?: string;

    ImageManifestDescriptor?: OCIDescriptor;

    /**
     * Command to run when starting the container
     */
    Command?: string;

    /**
     * Date and time at which the container was created as a Unix timestamp (number of seconds since EPOCH).
     */
    Created?: number;

    /**
     * Port-mappings for the container.
     */
    Ports?: Array<PortSummary>;

    /**
     * The size of files that have been created or changed by this container.  This field is omitted by default, and only set when size is requested in the API request.
     */
    SizeRw?: number | null;

    /**
     * The total size of all files in the read-only layers from the image that the container uses. These layers can be shared between containers.  This field is omitted by default, and only set when size is requested in the API request.
     */
    SizeRootFs?: number | null;

    /**
     * User-defined key/value metadata.
     */
    Labels?: { [key: string]: string };

    /**
     * The state of this container.
     */
    State?: ContainerSummaryStateEnum;

    /**
     * Additional human-readable status of this container (e.g. &#x60;Exit 0&#x60;)
     */
    Status?: string;

    HostConfig?: ContainerSummaryHostConfig;

    NetworkSettings?: ContainerSummaryNetworkSettings;

    /**
     * List of mounts used by the container.
     */
    Mounts?: Array<MountPoint>;

    Health?: ContainerSummaryHealth;
}

export type ContainerSummaryStateEnum =
    | 'created'
    | 'running'
    | 'paused'
    | 'restarting'
    | 'exited'
    | 'removing'
    | 'dead';
