/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type ContainerCPUUsage } from '../types/ContainerCPUUsage.js';
import { type ContainerThrottlingData } from '../types/ContainerThrottlingData.js';

/**
 * CPU related info of the container
 */
export interface ContainerCPUStats {
    cpu_usage?: ContainerCPUUsage | null;

    /**
     * System Usage.  This field is Linux-specific and omitted for Windows containers.
     */
    system_cpu_usage?: number | null;

    /**
     * Number of online CPUs.  This field is Linux-specific and omitted for Windows containers.
     */
    online_cpus?: number | null;

    throttling_data?: ContainerThrottlingData | null;
}
