/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * A request for devices to be sent to device drivers
 */
export interface DeviceRequest {
    /**
     * The name of the device driver to use for this request.  Note that if this is specified the capabilities are ignored when selecting a device driver.
     */
    Driver?: string;

    Count?: number;

    DeviceIDs?: Array<string>;

    /**
     * A list of capabilities; an OR list of AND lists of capabilities.  Note that if a driver is specified the capabilities have no effect on selecting a driver as the driver name is used directly.  Note that if no driver is specified the capabilities are used to select a driver with the required capabilities.
     */
    Capabilities?: Array<Array<string>>;

    /**
     * Driver-specific options, specified as a key/value pairs. These options are passed directly to the driver.
     */
    Options?: { [key: string]: string };
}
