/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

export interface EndpointPortConfig {
    Name?: string;

    Protocol?: EndpointPortConfigProtocolEnum;

    /**
     * The port inside the container.
     */
    TargetPort?: number;

    /**
     * The port on the swarm hosts.
     */
    PublishedPort?: number;

    /**
     * The mode in which port is published.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  - \&quot;ingress\&quot; makes the target port accessible on every node,   regardless of whether there is a task for the service running on   that node or not. - \&quot;host\&quot; bypasses the routing mesh and publish the port directly on   the swarm node where that service is running.
     */
    PublishMode?: EndpointPortConfigPublishModeEnum;
}

export type EndpointPortConfigProtocolEnum = 'tcp' | 'udp' | 'sctp';
export type EndpointPortConfigPublishModeEnum = 'ingress' | 'host';
