/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type HealthcheckResult } from '../types/HealthcheckResult.js';

/**
 * Health stores information about the container\'s healthcheck results.
 */
export interface Health {
    /**
     * Status is one of &#x60;none&#x60;, &#x60;starting&#x60;, &#x60;healthy&#x60; or &#x60;unhealthy&#x60;  - \&quot;none\&quot;      Indicates there is no healthcheck - \&quot;starting\&quot;  Starting indicates that the container is not yet ready - \&quot;healthy\&quot;   Healthy indicates that the container is running correctly - \&quot;unhealthy\&quot; Unhealthy indicates that the container has a problem
     */
    Status?: HealthStatusEnum;

    /**
     * FailingStreak is the number of consecutive failures
     */
    FailingStreak?: number;

    /**
     * Log contains the last few results (oldest first)
     */
    Log?: Array<HealthcheckResult>;
}

export type HealthStatusEnum = 'none' | 'starting' | 'healthy' | 'unhealthy';
