/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type HealthConfig } from '../types/HealthConfig.js';

/**
 * Configuration of the image. These fields are used as defaults when starting a container from the image.
 */
export interface ImageConfig {
    /**
     * The user that commands are run as inside the container.
     */
    User?: string;

    /**
     * An object mapping ports to an empty object in the form:  &#x60;{\&quot;&lt;port&gt;/&lt;tcp|udp|sctp&gt;\&quot;: {}}&#x60;
     */
    ExposedPorts?: { [key: string]: any } | null;

    /**
     * A list of environment variables to set inside the container in the form &#x60;[\&quot;VAR&#x3D;value\&quot;, ...]&#x60;. A variable without &#x60;&#x3D;&#x60; is removed from the environment, rather than to have an empty value.
     */
    Env?: Array<string>;

    /**
     * Command to run specified as a string or an array of strings.
     */
    Cmd?: Array<string>;

    Healthcheck?: HealthConfig;

    /**
     * Command is already escaped (Windows only)
     */
    ArgsEscaped?: boolean | null;

    /**
     * An object mapping mount point paths inside the container to empty objects.
     */
    Volumes?: { [key: string]: any };

    /**
     * The working directory for commands to run in.
     */
    WorkingDir?: string;

    /**
     * The entry point for the container as a string or an array of strings.  If the array consists of exactly one empty string (&#x60;[\&quot;\&quot;]&#x60;) then the entry point is reset to system default (i.e., the entry point used by docker when there is no &#x60;ENTRYPOINT&#x60; instruction in the &#x60;Dockerfile&#x60;).
     */
    Entrypoint?: Array<string>;

    /**
     * &#x60;ONBUILD&#x60; metadata that were defined in the image\&#39;s &#x60;Dockerfile&#x60;.
     */
    OnBuild?: Array<string> | null;

    /**
     * User-defined key/value metadata.
     */
    Labels?: { [key: string]: string };

    /**
     * Signal to stop a container as a string or unsigned integer.
     */
    StopSignal?: string | null;

    /**
     * Shell for when &#x60;RUN&#x60;, &#x60;CMD&#x60;, and &#x60;ENTRYPOINT&#x60; uses a shell.
     */
    Shell?: Array<string> | null;
}
