/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type DriverData } from '../types/DriverData.js';
import { type ImageConfig } from '../types/ImageConfig.js';
import { type ImageInspectMetadata } from '../types/ImageInspectMetadata.js';
import { type ImageInspectRootFS } from '../types/ImageInspectRootFS.js';
import { type ImageManifestSummary } from '../types/ImageManifestSummary.js';
import { type OCIDescriptor } from '../types/OCIDescriptor.js';

/**
 * Information about an image in the local image cache.
 */
export interface ImageInspect {
    /**
     * ID is the content-addressable ID of an image.  This identifier is a content-addressable digest calculated from the image\&#39;s configuration (which includes the digests of layers used by the image).  Note that this digest differs from the &#x60;RepoDigests&#x60; below, which holds digests of image manifests that reference the image.
     */
    Id?: string;

    Descriptor?: OCIDescriptor;

    /**
     * Manifests is a list of image manifests available in this image. It provides a more detailed view of the platform-specific image manifests or other image-attached data like build attestations.  Only available if the daemon provides a multi-platform image store and the &#x60;manifests&#x60; option is set in the inspect request.  WARNING: This is experimental and may change at any time without any backward compatibility.
     */
    Manifests?: Array<ImageManifestSummary> | null;

    /**
     * List of image names/tags in the local image cache that reference this image.  Multiple image tags can refer to the same image, and this list may be empty if no tags reference the image, in which case the image is \&quot;untagged\&quot;, in which case it can still be referenced by its ID.
     */
    RepoTags?: Array<string>;

    /**
     * List of content-addressable digests of locally available image manifests that the image is referenced from. Multiple manifests can refer to the same image.  These digests are usually only available if the image was either pulled from a registry, or if the image was pushed to a registry, which is when the manifest is generated and its digest calculated.
     */
    RepoDigests?: Array<string>;

    /**
     * ID of the parent image.  Depending on how the image was created, this field may be empty and is only set for images that were built/created locally. This field is empty if the image was pulled from an image registry.
     */
    Parent?: string;

    /**
     * Optional message that was set when committing or importing the image.
     */
    Comment?: string;

    /**
     * Date and time at which the image was created, formatted in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.  This information is only available if present in the image, and omitted otherwise.
     */
    Created?: string | null;

    /**
     * The version of Docker that was used to build the image.  Depending on how the image was created, this field may be empty.
     */
    DockerVersion?: string;

    /**
     * Name of the author that was specified when committing the image, or as specified through MAINTAINER (deprecated) in the Dockerfile.
     */
    Author?: string;

    Config?: ImageConfig;

    /**
     * Hardware CPU architecture that the image runs on.
     */
    Architecture?: string;

    /**
     * CPU architecture variant (presently ARM-only).
     */
    Variant?: string | null;

    /**
     * Operating System the image is built to run on.
     */
    Os?: string;

    /**
     * Operating System version the image is built to run on (especially for Windows).
     */
    OsVersion?: string | null;

    /**
     * Total size of the image including all layers it is composed of.
     */
    Size?: number;

    /**
     * Total size of the image including all layers it is composed of.  Deprecated: this field is omitted in API v1.44, but kept for backward compatibility. Use Size instead.
     */
    VirtualSize?: number;

    GraphDriver?: DriverData;

    RootFS?: ImageInspectRootFS;

    Metadata?: ImageInspectMetadata;
}
