/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type MountBindOptions } from '../types/MountBindOptions.js';
import { type MountImageOptions } from '../types/MountImageOptions.js';
import { type MountTmpfsOptions } from '../types/MountTmpfsOptions.js';
import { type MountVolumeOptions } from '../types/MountVolumeOptions.js';

export interface Mount {
    /**
     * Container path.
     */
    Target?: string;

    /**
     * Mount source (e.g. a volume name, a host path).
     */
    Source?: string;

    /**
     * The mount type. Available types:  - &#x60;bind&#x60; Mounts a file or directory from the host into the container. Must exist prior to creating the container. - &#x60;volume&#x60; Creates a volume with the given name and options (or uses a pre-existing volume with the same name and options). These are **not** removed when the container is removed. - &#x60;image&#x60; Mounts an image. - &#x60;tmpfs&#x60; Create a tmpfs with the given options. The mount source cannot be specified for tmpfs. - &#x60;npipe&#x60; Mounts a named pipe from the host into the container. Must exist prior to creating the container. - &#x60;cluster&#x60; a Swarm cluster volume
     */
    Type?: MountTypeEnum;

    /**
     * Whether the mount should be read-only.
     */
    ReadOnly?: boolean;

    /**
     * The consistency requirement for the mount: &#x60;default&#x60;, &#x60;consistent&#x60;, &#x60;cached&#x60;, or &#x60;delegated&#x60;.
     */
    Consistency?: string;

    BindOptions?: MountBindOptions;

    VolumeOptions?: MountVolumeOptions;

    ImageOptions?: MountImageOptions;

    TmpfsOptions?: MountTmpfsOptions;
}

export type MountTypeEnum =
    | 'bind'
    | 'volume'
    | 'image'
    | 'tmpfs'
    | 'npipe'
    | 'cluster';
