/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type Address } from '../types/Address.js';
import { type EndpointSettings } from '../types/EndpointSettings.js';
import { type PortBinding } from '../types/PortBinding.js';

/**
 * NetworkSettings exposes the network settings in the API
 */
export interface NetworkSettings {
    /**
     * Name of the default bridge interface when dockerd\&#39;s --bridge flag is set.  Deprecated: This field is only set when the daemon is started with the --bridge flag specified.
     */
    Bridge?: string;

    /**
     * SandboxID uniquely represents a container\&#39;s network stack.
     */
    SandboxID?: string;

    /**
     * Indicates if hairpin NAT should be enabled on the virtual interface.  Deprecated: This field is never set and will be removed in a future release.
     */
    HairpinMode?: boolean;

    /**
     * IPv6 unicast address using the link-local prefix.  Deprecated: This field is never set and will be removed in a future release.
     */
    LinkLocalIPv6Address?: string;

    /**
     * Prefix length of the IPv6 unicast address.  Deprecated: This field is never set and will be removed in a future release.
     */
    LinkLocalIPv6PrefixLen?: number;

    /**
     * PortMap describes the mapping of container ports to host ports, using the container\&#39;s port-number and protocol as key in the format &#x60;&lt;port&gt;/&lt;protocol&gt;&#x60;, for example, &#x60;80/udp&#x60;.  If a container\&#39;s port is mapped for multiple protocols, separate entries are added to the mapping table.
     */
    Ports?: { [key: string]: Array<PortBinding> | null };

    /**
     * SandboxKey is the full path of the netns handle
     */
    SandboxKey?: string;

    /**
     * Deprecated: This field is never set and will be removed in a future release.
     */
    SecondaryIPAddresses?: Array<Address> | null;

    /**
     * Deprecated: This field is never set and will be removed in a future release.
     */
    SecondaryIPv6Addresses?: Array<Address> | null;

    /**
     * EndpointID uniquely represents a service endpoint in a Sandbox.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: This field is only propagated when attached to the &gt; default \&quot;bridge\&quot; network. Use the information from the \&quot;bridge\&quot; &gt; network inside the &#x60;Networks&#x60; map instead, which contains the same &gt; information. This field was deprecated in Docker 1.9 and is scheduled &gt; to be removed in Docker 17.12.0
     */
    EndpointID?: string;

    /**
     * Gateway address for the default \&quot;bridge\&quot; network.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: This field is only propagated when attached to the &gt; default \&quot;bridge\&quot; network. Use the information from the \&quot;bridge\&quot; &gt; network inside the &#x60;Networks&#x60; map instead, which contains the same &gt; information. This field was deprecated in Docker 1.9 and is scheduled &gt; to be removed in Docker 17.12.0
     */
    Gateway?: string;

    /**
     * Global IPv6 address for the default \&quot;bridge\&quot; network.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: This field is only propagated when attached to the &gt; default \&quot;bridge\&quot; network. Use the information from the \&quot;bridge\&quot; &gt; network inside the &#x60;Networks&#x60; map instead, which contains the same &gt; information. This field was deprecated in Docker 1.9 and is scheduled &gt; to be removed in Docker 17.12.0
     */
    GlobalIPv6Address?: string;

    /**
     * Mask length of the global IPv6 address.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: This field is only propagated when attached to the &gt; default \&quot;bridge\&quot; network. Use the information from the \&quot;bridge\&quot; &gt; network inside the &#x60;Networks&#x60; map instead, which contains the same &gt; information. This field was deprecated in Docker 1.9 and is scheduled &gt; to be removed in Docker 17.12.0
     */
    GlobalIPv6PrefixLen?: number;

    /**
     * IPv4 address for the default \&quot;bridge\&quot; network.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: This field is only propagated when attached to the &gt; default \&quot;bridge\&quot; network. Use the information from the \&quot;bridge\&quot; &gt; network inside the &#x60;Networks&#x60; map instead, which contains the same &gt; information. This field was deprecated in Docker 1.9 and is scheduled &gt; to be removed in Docker 17.12.0
     */
    IPAddress?: string;

    /**
     * Mask length of the IPv4 address.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: This field is only propagated when attached to the &gt; default \&quot;bridge\&quot; network. Use the information from the \&quot;bridge\&quot; &gt; network inside the &#x60;Networks&#x60; map instead, which contains the same &gt; information. This field was deprecated in Docker 1.9 and is scheduled &gt; to be removed in Docker 17.12.0
     */
    IPPrefixLen?: number;

    /**
     * IPv6 gateway address for this network.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: This field is only propagated when attached to the &gt; default \&quot;bridge\&quot; network. Use the information from the \&quot;bridge\&quot; &gt; network inside the &#x60;Networks&#x60; map instead, which contains the same &gt; information. This field was deprecated in Docker 1.9 and is scheduled &gt; to be removed in Docker 17.12.0
     */
    IPv6Gateway?: string;

    /**
     * MAC address for the container on the default \&quot;bridge\&quot; network.  &lt;p&gt;&lt;br /&gt;&lt;/p&gt;  &gt; **Deprecated**: This field is only propagated when attached to the &gt; default \&quot;bridge\&quot; network. Use the information from the \&quot;bridge\&quot; &gt; network inside the &#x60;Networks&#x60; map instead, which contains the same &gt; information. This field was deprecated in Docker 1.9 and is scheduled &gt; to be removed in Docker 17.12.0
     */
    MacAddress?: string;

    /**
     * Information about all networks that the container is connected to.
     */
    Networks?: { [key: string]: EndpointSettings };
}
