/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type ManagerStatus } from '../types/ManagerStatus.js';
import { type NodeDescription } from '../types/NodeDescription.js';
import { type NodeSpec } from '../types/NodeSpec.js';
import { type NodeStatus } from '../types/NodeStatus.js';
import { type ObjectVersion } from '../types/ObjectVersion.js';

export interface Node {
    ID?: string;

    Version?: ObjectVersion;

    /**
     * Date and time at which the node was added to the swarm in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    CreatedAt?: string;

    /**
     * Date and time at which the node was last updated in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    UpdatedAt?: string;

    Spec?: NodeSpec;

    Description?: NodeDescription;

    Status?: NodeStatus;

    ManagerStatus?: ManagerStatus | null;
}
