/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

export interface SwarmSpecCAConfigExternalCAsInner {
    /**
     * Protocol for communication with the external CA (currently only &#x60;cfssl&#x60; is supported).
     */
    Protocol?: SwarmSpecCAConfigExternalCAsInnerProtocolEnum;

    /**
     * URL where certificate signing requests should be sent.
     */
    URL?: string;

    /**
     * An object with key/value pairs that are interpreted as protocol-specific options for the external CA driver.
     */
    Options?: { [key: string]: string };

    /**
     * The root CA certificate (in PEM format) this external CA uses to issue TLS certificates (assumed to be to the current swarm root CA certificate if not provided).
     */
    CACert?: string;
}

export type SwarmSpecCAConfigExternalCAsInnerProtocolEnum = 'cfssl';
