/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { type ClusterInfo } from '../types/ClusterInfo.js';
import { type LocalNodeState } from '../types/LocalNodeState.js';
import { type PeerNode } from '../types/PeerNode.js';

/**
 * Represents generic information about swarm.
 */
export interface SwarmInfo {
    /**
     * Unique identifier of for this node in the swarm.
     */
    NodeID?: string;

    /**
     * IP address at which this node can be reached by other nodes in the swarm.
     */
    NodeAddr?: string;

    LocalNodeState?: LocalNodeState;

    ControlAvailable?: boolean;

    Error?: string;

    /**
     * List of ID\&#39;s and addresses of other managers in the swarm.
     */
    RemoteManagers?: Array<PeerNode> | null;

    /**
     * Total number of nodes in the swarm.
     */
    Nodes?: number | null;

    /**
     * Total number of managers in the swarm.
     */
    Managers?: number | null;

    Cluster?: ClusterInfo | null;
}
