/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * BuildCache contains information about a build cache record.
 */
export interface BuildCache {
    /**
     * Unique ID of the build cache record.
     */
    ID?: string;

    /**
     * ID of the parent build cache record.  &gt; **Deprecated**: This field is deprecated, and omitted if empty.
     */
    Parent?: string | null;

    /**
     * List of parent build cache record IDs.
     */
    Parents?: Array<string> | null;

    /**
     * Cache record type.
     */
    Type?: BuildCacheTypeEnum;

    /**
     * Description of the build-step that produced the build cache.
     */
    Description?: string;

    /**
     * Indicates if the build cache is in use.
     */
    InUse?: boolean;

    /**
     * Indicates if the build cache is shared.
     */
    Shared?: boolean;

    /**
     * Amount of disk space used by the build cache (in bytes).
     */
    Size?: number;

    /**
     * Date and time at which the build cache was created in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    CreatedAt?: string;

    /**
     * Date and time at which the build cache was last used in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    LastUsedAt?: string | null;

    UsageCount?: number;
}

export type BuildCacheTypeEnum =
    | 'internal'
    | 'frontend'
    | 'source.local'
    | 'source.git.checkout'
    | 'exec.cachemount'
    | 'regular';
