/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Requirements for the accessible topology of the volume. These fields are optional. For an in-depth description of what these fields mean, see the CSI specification.
 */
export interface ClusterVolumeSpecAccessModeAccessibilityRequirements {
    /**
     * A list of required topologies, at least one of which the volume must be accessible from.
     */
    Requisite?: Array<{ [key: string]: string }>;

    /**
     * A list of topologies that the volume should attempt to be provisioned in.
     */
    Preferred?: Array<{ [key: string]: string }>;
}
