/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { ContainerConfig } from '../models/ContainerConfig.js';
import { ContainerState } from '../models/ContainerState.js';
import { DriverData } from '../models/DriverData.js';
import { HostConfig } from '../models/HostConfig.js';
import { MountPoint } from '../models/MountPoint.js';
import { NetworkSettings } from '../models/NetworkSettings.js';
import { OCIDescriptor } from '../models/OCIDescriptor.js';

export interface ContainerInspectResponse {
    /**
     * The ID of this container as a 128-bit (64-character) hexadecimal string (32 bytes).
     */
    Id?: string;

    /**
     * Date and time at which the container was created, formatted in [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format with nano-seconds.
     */
    Created?: string | null;

    /**
     * The path to the command being run
     */
    Path?: string;

    /**
     * The arguments to the command being run
     */
    Args?: Array<string>;

    State?: ContainerState | null;

    /**
     * The ID (digest) of the image that this container was created from.
     */
    Image?: string;

    /**
     * Location of the &#x60;/etc/resolv.conf&#x60; generated for the container on the host.  This file is managed through the docker daemon, and should not be accessed or modified by other tools.
     */
    ResolvConfPath?: string;

    /**
     * Location of the &#x60;/etc/hostname&#x60; generated for the container on the host.  This file is managed through the docker daemon, and should not be accessed or modified by other tools.
     */
    HostnamePath?: string;

    /**
     * Location of the &#x60;/etc/hosts&#x60; generated for the container on the host.  This file is managed through the docker daemon, and should not be accessed or modified by other tools.
     */
    HostsPath?: string;

    /**
     * Location of the file used to buffer the container\&#39;s logs. Depending on the logging-driver used for the container, this field may be omitted.  This file is managed through the docker daemon, and should not be accessed or modified by other tools.
     */
    LogPath?: string | null;

    /**
     * The name associated with this container.  For historic reasons, the name may be prefixed with a forward-slash (&#x60;/&#x60;).
     */
    Name?: string;

    /**
     * Number of times the container was restarted since it was created, or since daemon was started.
     */
    RestartCount?: number;

    /**
     * The storage-driver used for the container\&#39;s filesystem (graph-driver or snapshotter).
     */
    Driver?: string;

    /**
     * The platform (operating system) for which the container was created.  This field was introduced for the experimental \&quot;LCOW\&quot; (Linux Containers On Windows) features, which has been removed. In most cases, this field is equal to the host\&#39;s operating system (&#x60;linux&#x60; or &#x60;windows&#x60;).
     */
    Platform?: string;

    ImageManifestDescriptor?: OCIDescriptor;

    /**
     * SELinux mount label set for the container.
     */
    MountLabel?: string;

    /**
     * SELinux process label set for the container.
     */
    ProcessLabel?: string;

    /**
     * The AppArmor profile set for the container.
     */
    AppArmorProfile?: string;

    /**
     * IDs of exec instances that are running in the container.
     */
    ExecIDs?: Array<string> | null;

    HostConfig?: HostConfig;

    GraphDriver?: DriverData;

    /**
     * The size of files that have been created or changed by this container.  This field is omitted by default, and only set when size is requested in the API request.
     */
    SizeRw?: number | null;

    /**
     * The total size of all files in the read-only layers from the image that the container uses. These layers can be shared between containers.  This field is omitted by default, and only set when size is requested in the API request.
     */
    SizeRootFs?: number | null;

    /**
     * List of mounts used by the container.
     */
    Mounts?: Array<MountPoint>;

    Config?: ContainerConfig;

    NetworkSettings?: NetworkSettings;
}
