/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { ContainerBlkioStats } from '../models/ContainerBlkioStats.js';
import { ContainerCPUStats } from '../models/ContainerCPUStats.js';
import { ContainerMemoryStats } from '../models/ContainerMemoryStats.js';
import { ContainerPidsStats } from '../models/ContainerPidsStats.js';
import { ContainerStorageStats } from '../models/ContainerStorageStats.js';

/**
 * Statistics sample for a container.
 */
export interface ContainerStatsResponse {
    /**
     * Name of the container
     */
    Name?: string | null;

    /**
     * ID of the container
     */
    Id?: string | null;

    /**
     * Date and time at which this sample was collected. The value is formatted as [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) with nano-seconds.
     */
    Read?: Date;

    /**
     * Date and time at which this first sample was collected. This field is not propagated if the \&quot;one-shot\&quot; option is set. If the \&quot;one-shot\&quot; option is set, this field may be omitted, empty, or set to a default date (&#x60;0001-01-01T00:00:00Z&#x60;).  The value is formatted as [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) with nano-seconds.
     */
    Preread?: Date;

    PidsStats?: ContainerPidsStats | null;

    BlkioStats?: ContainerBlkioStats | null;

    /**
     * The number of processors on the system.  This field is Windows-specific and always zero for Linux containers.
     */
    NumProcs?: number;

    StorageStats?: ContainerStorageStats | null;

    CpuStats?: ContainerCPUStats | null;

    PrecpuStats?: ContainerCPUStats | null;

    MemoryStats?: ContainerMemoryStats;

    /**
     * Network statistics for the container per interface.  This field is omitted if the container has no networking enabled.
     */
    Networks?: any | null;
}
