/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { ContainerBlkioStatEntry } from '../models/ContainerBlkioStatEntry.js';

/**
 * BlkioStats stores all IO service stats for data read and write.  This type is Linux-specific and holds many fields that are specific to cgroups v1. On a cgroup v2 host, all fields other than `io_service_bytes_recursive` are omitted or `null`.  This type is only populated on Linux and omitted for Windows containers.
 */
export interface ContainerBlkioStats {
    IoServiceBytesRecursive?: Array<ContainerBlkioStatEntry>;

    /**
     * This field is only available when using Linux containers with cgroups v1. It is omitted or &#x60;null&#x60; when using cgroups v2.
     */
    IoServicedRecursive?: Array<ContainerBlkioStatEntry> | null;

    /**
     * This field is only available when using Linux containers with cgroups v1. It is omitted or &#x60;null&#x60; when using cgroups v2.
     */
    IoQueueRecursive?: Array<ContainerBlkioStatEntry> | null;

    /**
     * This field is only available when using Linux containers with cgroups v1. It is omitted or &#x60;null&#x60; when using cgroups v2.
     */
    IoServiceTimeRecursive?: Array<ContainerBlkioStatEntry> | null;

    /**
     * This field is only available when using Linux containers with cgroups v1. It is omitted or &#x60;null&#x60; when using cgroups v2.
     */
    IoWaitTimeRecursive?: Array<ContainerBlkioStatEntry> | null;

    /**
     * This field is only available when using Linux containers with cgroups v1. It is omitted or &#x60;null&#x60; when using cgroups v2.
     */
    IoMergedRecursive?: Array<ContainerBlkioStatEntry> | null;

    /**
     * This field is only available when using Linux containers with cgroups v1. It is omitted or &#x60;null&#x60; when using cgroups v2.
     */
    IoTimeRecursive?: Array<ContainerBlkioStatEntry> | null;

    /**
     * This field is only available when using Linux containers with cgroups v1. It is omitted or &#x60;null&#x60; when using cgroups v2.
     */
    SectorsRecursive?: Array<ContainerBlkioStatEntry> | null;
}
