/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { DeviceMapping } from '../models/DeviceMapping.js';
import { DeviceRequest } from '../models/DeviceRequest.js';
import { ResourcesBlkioWeightDeviceInner } from '../models/ResourcesBlkioWeightDeviceInner.js';
import { ResourcesUlimitsInner } from '../models/ResourcesUlimitsInner.js';
import { RestartPolicy } from '../models/RestartPolicy.js';
import { ThrottleDevice } from '../models/ThrottleDevice.js';

export interface ContainerUpdateRequest {
    /**
     * An integer value representing this container\&#39;s relative CPU weight versus other containers.
     */
    CpuShares?: number;

    /**
     * Memory limit in bytes.
     */
    Memory?: number;

    /**
     * Path to &#x60;cgroups&#x60; under which the container\&#39;s &#x60;cgroup&#x60; is created. If the path is not absolute, the path is considered to be relative to the &#x60;cgroups&#x60; path of the init process. Cgroups are created if they do not already exist.
     */
    CgroupParent?: string;

    /**
     * Block IO weight (relative weight).
     */
    BlkioWeight?: number;

    /**
     * Block IO weight (relative device weight) in the form:  &#x60;&#x60;&#x60; [{\&quot;Path\&quot;: \&quot;device_path\&quot;, \&quot;Weight\&quot;: weight}] &#x60;&#x60;&#x60;
     */
    BlkioWeightDevice?: Array<ResourcesBlkioWeightDeviceInner>;

    /**
     * Limit read rate (bytes per second) from a device, in the form:  &#x60;&#x60;&#x60; [{\&quot;Path\&quot;: \&quot;device_path\&quot;, \&quot;Rate\&quot;: rate}] &#x60;&#x60;&#x60;
     */
    BlkioDeviceReadBps?: Array<ThrottleDevice>;

    /**
     * Limit write rate (bytes per second) to a device, in the form:  &#x60;&#x60;&#x60; [{\&quot;Path\&quot;: \&quot;device_path\&quot;, \&quot;Rate\&quot;: rate}] &#x60;&#x60;&#x60;
     */
    BlkioDeviceWriteBps?: Array<ThrottleDevice>;

    /**
     * Limit read rate (IO per second) from a device, in the form:  &#x60;&#x60;&#x60; [{\&quot;Path\&quot;: \&quot;device_path\&quot;, \&quot;Rate\&quot;: rate}] &#x60;&#x60;&#x60;
     */
    BlkioDeviceReadIOps?: Array<ThrottleDevice>;

    /**
     * Limit write rate (IO per second) to a device, in the form:  &#x60;&#x60;&#x60; [{\&quot;Path\&quot;: \&quot;device_path\&quot;, \&quot;Rate\&quot;: rate}] &#x60;&#x60;&#x60;
     */
    BlkioDeviceWriteIOps?: Array<ThrottleDevice>;

    /**
     * The length of a CPU period in microseconds.
     */
    CpuPeriod?: number;

    /**
     * Microseconds of CPU time that the container can get in a CPU period.
     */
    CpuQuota?: number;

    /**
     * The length of a CPU real-time period in microseconds. Set to 0 to allocate no time allocated to real-time tasks.
     */
    CpuRealtimePeriod?: number;

    /**
     * The length of a CPU real-time runtime in microseconds. Set to 0 to allocate no time allocated to real-time tasks.
     */
    CpuRealtimeRuntime?: number;

    /**
     * CPUs in which to allow execution (e.g., &#x60;0-3&#x60;, &#x60;0,1&#x60;).
     */
    CpusetCpus?: string;

    /**
     * Memory nodes (MEMs) in which to allow execution (0-3, 0,1). Only effective on NUMA systems.
     */
    CpusetMems?: string;

    /**
     * A list of devices to add to the container.
     */
    Devices?: Array<DeviceMapping>;

    /**
     * a list of cgroup rules to apply to the container
     */
    DeviceCgroupRules?: Array<string>;

    /**
     * A list of requests for devices to be sent to device drivers.
     */
    DeviceRequests?: Array<DeviceRequest>;

    /**
     * Hard limit for kernel TCP buffer memory (in bytes). Depending on the OCI runtime in use, this option may be ignored. It is no longer supported by the default (runc) runtime.  This field is omitted when empty.
     */
    KernelMemoryTCP?: number;

    /**
     * Memory soft limit in bytes.
     */
    MemoryReservation?: number;

    /**
     * Total memory limit (memory + swap). Set as &#x60;-1&#x60; to enable unlimited swap.
     */
    MemorySwap?: number;

    /**
     * Tune a container\&#39;s memory swappiness behavior. Accepts an integer between 0 and 100.
     */
    MemorySwappiness?: number;

    /**
     * CPU quota in units of 10&lt;sup&gt;-9&lt;/sup&gt; CPUs.
     */
    NanoCpus?: number;

    /**
     * Disable OOM Killer for the container.
     */
    OomKillDisable?: boolean;

    /**
     * Run an init inside the container that forwards signals and reaps processes. This field is omitted if empty, and the default (as configured on the daemon) is used.
     */
    Init?: boolean | null;

    /**
     * Tune a container\&#39;s PIDs limit. Set &#x60;0&#x60; or &#x60;-1&#x60; for unlimited, or &#x60;null&#x60; to not change.
     */
    PidsLimit?: number | null;

    /**
     * A list of resource limits to set in the container. For example:  &#x60;&#x60;&#x60; {\&quot;Name\&quot;: \&quot;nofile\&quot;, \&quot;Soft\&quot;: 1024, \&quot;Hard\&quot;: 2048} &#x60;&#x60;&#x60;
     */
    Ulimits?: Array<ResourcesUlimitsInner>;

    /**
     * The number of usable CPUs (Windows only).  On Windows Server containers, the processor resource controls are mutually exclusive. The order of precedence is &#x60;CPUCount&#x60; first, then &#x60;CPUShares&#x60;, and &#x60;CPUPercent&#x60; last.
     */
    CpuCount?: number;

    /**
     * The usable percentage of the available CPUs (Windows only).  On Windows Server containers, the processor resource controls are mutually exclusive. The order of precedence is &#x60;CPUCount&#x60; first, then &#x60;CPUShares&#x60;, and &#x60;CPUPercent&#x60; last.
     */
    CpuPercent?: number;

    /**
     * Maximum IOps for the container system drive (Windows only)
     */
    IOMaximumIOps?: number;

    /**
     * Maximum IO in bytes per second for the container system drive (Windows only).
     */
    IOMaximumBandwidth?: number;

    RestartPolicy?: RestartPolicy;
}
