/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Aggregates all memory stats since container inception on Linux. Windows returns stats for commit and private working set only.
 */
export interface ContainerMemoryStats {
    /**
     * Current &#x60;res_counter&#x60; usage for memory.  This field is Linux-specific and omitted for Windows containers.
     */
    Usage?: number | null;

    /**
     * Maximum usage ever recorded.  This field is Linux-specific and only supported on cgroups v1. It is omitted when using cgroups v2 and for Windows containers.
     */
    MaxUsage?: number | null;

    /**
     * All the stats exported via memory.stat. when using cgroups v2.  This field is Linux-specific and omitted for Windows containers.
     */
    Stats?: { [key: string]: number | null };

    /**
     * Number of times memory usage hits limits.  This field is Linux-specific and only supported on cgroups v1. It is omitted when using cgroups v2 and for Windows containers.
     */
    Failcnt?: number | null;

    /**
     * This field is Linux-specific and omitted for Windows containers.
     */
    Limit?: number | null;

    /**
     * Committed bytes.  This field is Windows-specific and omitted for Linux containers.
     */
    Commitbytes?: number | null;

    /**
     * Peak committed bytes.  This field is Windows-specific and omitted for Linux containers.
     */
    Commitpeakbytes?: number | null;

    /**
     * Private working set.  This field is Windows-specific and omitted for Linux containers.
     */
    Privateworkingset?: number | null;
}
