/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { EndpointPortConfig } from '../models/EndpointPortConfig.js';

/**
 * Properties that can be configured to access and load balance a service.
 */
export interface EndpointSpec {
    /**
     * The mode of resolution to use for internal load balancing between tasks.
     */
    Mode?: EndpointSpecModeEnum;

    /**
     * List of exposed ports that this service is accessible on from the outside. Ports can only be provided if &#x60;vip&#x60; resolution mode is used.
     */
    Ports?: Array<EndpointPortConfig>;
}

export type EndpointSpecModeEnum = 'vip' | 'dnsrr';
