/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

export interface ExecConfig {
    /**
     * Attach to &#x60;stdin&#x60; of the exec command.
     */
    AttachStdin?: boolean;

    /**
     * Attach to &#x60;stdout&#x60; of the exec command.
     */
    AttachStdout?: boolean;

    /**
     * Attach to &#x60;stderr&#x60; of the exec command.
     */
    AttachStderr?: boolean;

    /**
     * Initial console size, as an &#x60;[height, width]&#x60; array.
     */
    ConsoleSize?: Array<number> | null;

    /**
     * Override the key sequence for detaching a container. Format is a single character &#x60;[a-Z]&#x60; or &#x60;ctrl-&lt;value&gt;&#x60; where &#x60;&lt;value&gt;&#x60; is one of: &#x60;a-z&#x60;, &#x60;@&#x60;, &#x60;^&#x60;, &#x60;[&#x60;, &#x60;,&#x60; or &#x60;_&#x60;.
     */
    DetachKeys?: string;

    /**
     * Allocate a pseudo-TTY.
     */
    Tty?: boolean;

    /**
     * A list of environment variables in the form &#x60;[\&quot;VAR&#x3D;value\&quot;, ...]&#x60;.
     */
    Env?: Array<string>;

    /**
     * Command to run, as a string or array of strings.
     */
    Cmd?: Array<string>;

    /**
     * Runs the exec process with extended privileges.
     */
    Privileged?: boolean;

    /**
     * The user, and optionally, group to run the exec process inside the container. Format is one of: &#x60;user&#x60;, &#x60;user:group&#x60;, &#x60;uid&#x60;, or &#x60;uid:gid&#x60;.
     */
    User?: string;

    /**
     * The working directory for the exec process inside the container.
     */
    WorkingDir?: string;
}
