/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

export interface ImageManifestSummaryImageDataSize {
    /**
     * Unpacked is the size (in bytes) of the locally unpacked (uncompressed) image content that\&#39;s directly usable by the containers running this image. It\&#39;s independent of the distributable content - e.g. the image might still have an unpacked data that\&#39;s still used by some container even when the distributable/compressed content is already gone.
     */
    Unpacked: number;
}
