/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * IndexInfo contains information about a registry.
 */
export interface IndexInfo {
    /**
     * Name of the registry, such as \&quot;docker.io\&quot;.
     */
    Name?: string;

    /**
     * List of mirrors, expressed as URIs.
     */
    Mirrors?: Array<string>;

    /**
     * Indicates if the registry is part of the list of insecure registries.  If &#x60;false&#x60;, the registry is insecure. Insecure registries accept un-encrypted (HTTP) and/or untrusted (HTTPS with certificates from unknown CAs) communication.  &gt; **Warning**: Insecure registries can be useful when running a local &gt; registry. However, because its use creates security vulnerabilities &gt; it should ONLY be enabled for testing purposes. For increased &gt; security, users should add their CA to their system\&#39;s list of &gt; trusted CAs instead of enabling this option.
     */
    Secure?: boolean;

    /**
     * Indicates whether this is an official registry (i.e., Docker Hub / docker.io)
     */
    Official?: boolean;
}
