/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Optional configuration for the `bind` type.
 */
export interface MountBindOptions {
    /**
     * A propagation mode with the value &#x60;[r]private&#x60;, &#x60;[r]shared&#x60;, or &#x60;[r]slave&#x60;.
     */
    Propagation?: MountBindOptionsPropagationEnum;

    /**
     * Disable recursive bind mount.
     */
    NonRecursive?: boolean;

    /**
     * Create mount point on host if missing
     */
    CreateMountpoint?: boolean;

    /**
     * Make the mount non-recursively read-only, but still leave the mount recursive (unless NonRecursive is set to &#x60;true&#x60; in conjunction).  Added in v1.44, before that version all read-only mounts were non-recursive by default. To match the previous behaviour this will default to &#x60;true&#x60; for clients on versions prior to v1.44.
     */
    ReadOnlyNonRecursive?: boolean;

    /**
     * Raise an error if the mount cannot be made recursively read-only.
     */
    ReadOnlyForceRecursive?: boolean;
}

export type MountBindOptionsPropagationEnum =
    | 'private'
    | 'rprivate'
    | 'shared'
    | 'rshared'
    | 'slave'
    | 'rslave';
