/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Specification for the update strategy of the service.
 */
export interface ServiceSpecUpdateConfig {
    /**
     * Maximum number of tasks to be updated in one iteration (0 means unlimited parallelism).
     */
    Parallelism?: number;

    /**
     * Amount of time between updates, in nanoseconds.
     */
    Delay?: number;

    /**
     * Action to take if an updated task fails to run, or stops running during the update.
     */
    FailureAction?: ServiceSpecUpdateConfigFailureActionEnum;

    /**
     * Amount of time to monitor each updated task for failures, in nanoseconds.
     */
    Monitor?: number;

    /**
     * The fraction of tasks that may fail during an update before the failure action is invoked, specified as a floating point number between 0 and 1.
     */
    MaxFailureRatio?: number;

    /**
     * The order of operations when rolling out an updated task. Either the old task is shut down before the new task is started, or the new task is started before the old task is shut down.
     */
    Order?: ServiceSpecUpdateConfigOrderEnum;
}

export type ServiceSpecUpdateConfigFailureActionEnum =
    | 'continue'
    | 'pause'
    | 'rollback';
export type ServiceSpecUpdateConfigOrderEnum = 'stop-first' | 'start-first';
