/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { ObjectVersion } from '../models/ObjectVersion.js';
import { ServiceEndpoint } from '../models/ServiceEndpoint.js';
import { ServiceJobStatus } from '../models/ServiceJobStatus.js';
import { ServiceServiceStatus } from '../models/ServiceServiceStatus.js';
import { ServiceSpec } from '../models/ServiceSpec.js';
import { ServiceUpdateStatus } from '../models/ServiceUpdateStatus.js';

export interface Service {
    ID?: string;

    Version?: ObjectVersion;

    CreatedAt?: string;

    UpdatedAt?: string;

    Spec?: ServiceSpec;

    Endpoint?: ServiceEndpoint;

    UpdateStatus?: ServiceUpdateStatus;

    ServiceStatus?: ServiceServiceStatus;

    JobStatus?: ServiceJobStatus;
}
