/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { GenericResourcesInner } from '../models/GenericResourcesInner.js';
import { ObjectVersion } from '../models/ObjectVersion.js';
import { TaskSpec } from '../models/TaskSpec.js';
import { TaskState } from '../models/TaskState.js';
import { TaskStatus } from '../models/TaskStatus.js';

export interface Task {
    /**
     * The ID of the task.
     */
    ID?: string;

    Version?: ObjectVersion;

    CreatedAt?: string;

    UpdatedAt?: string;

    /**
     * Name of the task.
     */
    Name?: string;

    /**
     * User-defined key/value metadata.
     */
    Labels?: { [key: string]: string };

    Spec?: TaskSpec;

    /**
     * The ID of the service this task is part of.
     */
    ServiceID?: string;

    Slot?: number;

    /**
     * The ID of the node that this task is on.
     */
    NodeID?: string;

    /**
     * User-defined resources can be either Integer resources (e.g, &#x60;SSD&#x3D;3&#x60;) or String resources (e.g, &#x60;GPU&#x3D;UUID1&#x60;).
     */
    AssignedGenericResources?: Array<GenericResourcesInner>;

    Status?: TaskStatus;

    DesiredState?: TaskState;

    JobIteration?: ObjectVersion;
}
