/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * Specification for the restart policy which applies to containers created as part of this service.
 */
export interface TaskSpecRestartPolicy {
    /**
     * Condition for restart.
     */
    Condition?: TaskSpecRestartPolicyConditionEnum;

    /**
     * Delay between restart attempts.
     */
    Delay?: number;

    /**
     * Maximum attempts to restart a given container before giving up (default value is 0, which is ignored).
     */
    MaxAttempts?: number;

    /**
     * Windows is the time window used to evaluate the restart policy (default value is 0, which is unbounded).
     */
    Window?: number;
}

export type TaskSpecRestartPolicyConditionEnum = 'none' | 'on-failure' | 'any';
