/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { NetworkAttachmentConfig } from '../models/NetworkAttachmentConfig.js';
import { TaskSpecContainerSpec } from '../models/TaskSpecContainerSpec.js';
import { TaskSpecLogDriver } from '../models/TaskSpecLogDriver.js';
import { TaskSpecNetworkAttachmentSpec } from '../models/TaskSpecNetworkAttachmentSpec.js';
import { TaskSpecPlacement } from '../models/TaskSpecPlacement.js';
import { TaskSpecPluginSpec } from '../models/TaskSpecPluginSpec.js';
import { TaskSpecResources } from '../models/TaskSpecResources.js';
import { TaskSpecRestartPolicy } from '../models/TaskSpecRestartPolicy.js';

/**
 * User modifiable task configuration.
 */
export interface TaskSpec {
    PluginSpec?: TaskSpecPluginSpec;

    ContainerSpec?: TaskSpecContainerSpec;

    NetworkAttachmentSpec?: TaskSpecNetworkAttachmentSpec;

    Resources?: TaskSpecResources;

    RestartPolicy?: TaskSpecRestartPolicy;

    Placement?: TaskSpecPlacement;

    /**
     * A counter that triggers an update even if no relevant parameters have been changed.
     */
    ForceUpdate?: number;

    /**
     * Runtime is the type of runtime specified for the task executor.
     */
    Runtime?: string;

    /**
     * Specifies which networks the service should attach to.
     */
    Networks?: Array<NetworkAttachmentConfig>;

    LogDriver?: TaskSpecLogDriver;
}
