/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

/**
 * File represents a specific target that is backed by a file.  <p><br /><p>  > **Note**: `Configs.File` and `Configs.Runtime` are mutually exclusive
 */
export interface TaskSpecContainerSpecConfigsInnerFile {
    /**
     * Name represents the final filename in the filesystem.
     */
    Name?: string;

    /**
     * UID represents the file UID.
     */
    UID?: string;

    /**
     * GID represents the file GID.
     */
    GID?: string;

    /**
     * Mode represents the FileMode of the file.
     */
    Mode?: number;
}
