/*
   Copyright 2025 Docker SDK authors

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
   https://openapi-generator.tech
   Do not edit the class manually.
 */

import { ClusterVolumeSpec } from '../models/ClusterVolumeSpec.js';

/**
 * Volume configuration
 */
export interface VolumeCreateOptions {
    /**
     * The new volume\&#39;s name. If not specified, Docker generates a name.
     */
    Name?: string;

    /**
     * Name of the volume driver to use.
     */
    Driver?: string;

    /**
     * A mapping of driver options and values. These options are passed directly to the driver and are driver specific.
     */
    DriverOpts?: { [key: string]: string };

    /**
     * User-defined key/value metadata.
     */
    Labels?: { [key: string]: string };

    ClusterVolumeSpec?: ClusterVolumeSpec;
}
