name: ci

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches:
            - "main"
    pull_request:

permissions:
    contents: read # to fetch code (actions/checkout)

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install
              run: |
                  npm install
            - name: Format Check
              run: |
                  npm run format.check
            - name: Type Check
              run: |
                  npm run typecheck
            - name: Test
              run: |
                  npm test
            - name: Integration Test - ESM Import
              working-directory: ./test-integration/esm-project
              run: |
                  npm install
                  npm run test
            - name: Integration Test - CJS Import
              working-directory: ./test-integration/esm-project
              run: |
                  npm install
                  npm run test
