name: Publish Package

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Semver version to publish"
                type: string
                required: true
            dryRun:
                description: "Enable dry run (default: true)"
                type: boolean
                default: true
#    push:
#        tags:
#            - "v*"

permissions:
    id-token: write # Required for OIDC
    contents: write # Required to create git tags

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            # Uses NPM Trusted Publishers for access to the registry
            # See https://docs.npmjs.com/trusted-publishers
            - uses: actions/setup-node@v4
              with:
                  node-version-file: .node-version
                  registry-url: https://registry.npmjs.org

            # Ensure npm 11.5.1 or later is installed
            - name: Update npm
              run: npm install -g npm@11.6.1

            - name: Install
              run: npm ci

            - name: Build
              run: npm run build

            - name: Test
              run: npm test

            - name: Configure Git
              run: |
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                  git config --global user.name "${GITHUB_ACTOR}"

            - name: Version (dry-run)
              if: ${{ inputs.dryRun }}
              run: npm version --no-git-tag-version "${{ inputs.version }}"

            - name: Version
              if: ${{ ! inputs.dryRun }}
              run: npm version "${{ inputs.version }}"

            - name: Publish (dry-run)
              if: ${{ inputs.dryRun }}
              run: npm publish --provenance --access public --dry-run

            - name: Publish
              if: ${{ ! inputs.dryRun }}
              run: npm publish --provenance --access public

            - name: Push Tag
              if: ${{ ! inputs.dryRun }}
              run: git push origin v"${{ inputs.version }}"

            - name: GitHub Release
              if: ${{ ! inputs.dryRun }}
              uses: ncipollo/release-action@v1.20.0
              with:
                  generateReleaseNotes: true
                  makeLatest: true
                  token: ${{ secrets.GITHUB_TOKEN }}

            - uses: actions/setup-node@v4
              with:
                  node-version-file: .node-version
                  registry-url: https://npm.pkg.github.com
                  always-auth: 'true'

            - name: Publish (internal)
              if: ${{ ! inputs.dryRun }}
              run: |
                  npm publish --provenance

